### ISSUE TITLE
Anytone AdresTool v 1.00.rar

### ISSUE THREAD

**Issue by M6NBP** [PD1LOI/md380tools#1]
Hi and first of all thanks your hard work 

We have seen many in the UK that have changed there Call for new ones, still showing up with the old info.

Could you do a full fresh pull to see if this sorts out the issue. 

Many thanks 

Norman

**Comment by PD1LOI** [comment]
Always pass all changes to pd1wp.apeldoorn@gmail.com because we do not receive any change.

**Comment by M6NBP** [comment]
Sent
